const UserActionTypes = {
  FETCH_USER_START: 'FETCH_USER_START',
  GOOGLE_SINGIN_START: 'GOOGLE_SINGIN_START',
  SINGIN_SUCESS: 'SINGIN_SUCESS',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCESS: 'SIGN_OUT_SUCESS',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCESS: 'SIGN_UP_SUCESS',
  SIGN_FAILURE: 'SIGN_UP_FAILURE'
};

export default UserActionTypes